#!/usr/bin/env python3
"""
Create one note with audio.  GUID doesn't change!
"""

import genanki

from models import VOCAB_REVERSE2


class VocabNote(genanki.Note):
    """
    The Swahili audio shouldn't influence the GUID
    """

    @property
    def guid(self):
        return genanki.guid_for(self.fields[0], self.fields[1])


def main():
    """
    Generate Anki deck
    """

    deck = genanki.Deck(1334343228801, "TEST Swahili")

    output = "test2.apkg"
    swahili = genanki.Package(deck)
    swahili.media_files = ['Sw-ke-moja.opus']
    note = VocabNote(
                model=VOCAB_REVERSE2,
                fields=['moja (number)', 'one', '[sound:Sw-ke-moja.opus]'],
                )
    deck.add_note(note)
    swahili.write_to_file(output)


if __name__ == "__main__":
    main()
